### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Smruti1919** [G6EJD/ESP32-Morse-Decoder#1]
Arduino: 1.8.9 (Windows 10), Board: "Arduino/Genuino Uno"

WARNING: library Adafruit_Motor_Shield_Library claims to run on (esp8266, esp32) architecture(s) and may be incompatible with your current board which runs on (avr) architecture(s).
In file included from C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106.h:33:0,

                 from C:\Users\S K\Documents\Arduino\MICROP.ino\MICROP.ino.ino:1:

C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106Wire.h: In member function 'virtual bool SH1106Wire::connect()':

C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106Wire.h:59:40: error: no matching function for call to 'TwoWire::begin(uint8_t&, uint8_t&)'

       Wire.begin(this->_sda, this->_scl);

                                        ^

In file included from C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106Wire.h:35:0,

                 from C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106.h:33,

                 from C:\Users\S K\Documents\Arduino\MICROP.ino\MICROP.ino.ino:1:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:52:10: note: candidate: void TwoWire::begin()

     void begin();

          ^

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:52:10: note:   candidate expects 0 arguments, 2 provided

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:53:10: note: candidate: void TwoWire::begin(uint8_t)

     void begin(uint8_t);

          ^

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:53:10: note:   candidate expects 1 argument, 2 provided

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:54:10: note: candidate: void TwoWire::begin(int)

     void begin(int);

          ^

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:54:10: note:   candidate expects 1 argument, 2 provided

In file included from C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106.h:33:0,

                 from C:\Users\S K\Documents\Arduino\MICROP.ino\MICROP.ino.ino:1:

C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106Wire.h: In member function 'virtual void SH1106Wire::display()':

C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106Wire.h:82:43: error: '_min' was not declared in this scope

              minBoundY = _min(minBoundY, y);

                                           ^

C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106Wire.h:83:43: error: '_max' was not declared in this scope

              maxBoundY = _max(maxBoundY, y);

                                           ^

C:\Users\S K\Documents\Arduino\MICROP.ino\MICROP.ino.ino: In function 'void setup()':

MICROP.ino:45:23: error: no matching function for call to 'TwoWire::begin(int, int)'

   TwoWire::begin(17,16); // SDA, SCL

                       ^

In file included from C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106Wire.h:35:0,

                 from C:\Users\S K\Documents\Arduino\libraries\Adafruit_Motor_Shield_Library\src/SH1106.h:33,

                 from C:\Users\S K\Documents\Arduino\MICROP.ino\MICROP.ino.ino:1:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:52:10: note: candidate: void TwoWire::begin()

     void begin();

          ^

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:52:10: note:   candidate expects 0 arguments, 2 provided

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:53:10: note: candidate: void TwoWire::begin(uint8_t)

     void begin(uint8_t);

          ^

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:53:10: note:   candidate expects 1 argument, 2 provided

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:54:10: note: candidate: void TwoWire::begin(int)

     void begin(int);

          ^

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src/Wire.h:54:10: note:   candidate expects 1 argument, 2 provided

exit status 1
no matching function for call to 'TwoWire::begin(int, int)'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by G6EJD** [comment]
It would be more helpful if you had said what the issue was rather than copying the compiler log here. You can’t run this code on the UNO only an ESP32 or ESP8266.

**Comment by Smruti1919** [comment]
A fatal error occurred: Timed out waiting for packet content

**Comment by G6EJD** [comment]
What board type are you using?

**Comment by Smruti1919** [comment]
ESP32, After trying so long Code has been uploaded but OLED dosent display anything

**Comment by Smruti1919** [comment]
Is there anyway I can use a LCD instead of OLED

**Comment by G6EJD** [comment]
Is the microphone adjusted correctly? Are you using correct morse code?

**Comment by Smruti1919** [comment]
How is to be adjusted ?

**Comment by Smruti1919** [comment]
And AO pin of microphone unit should be connected to which pin esp32 ?

**Comment by Smruti1919** [comment]
> How is to be adjusted ?

I have been moving it clockwise but it keeps on rotating

**Comment by Smruti1919** [comment]
> And AO pin of microphone unit should be connected to which pin esp32 ?

Is it the SW pin ?

**Comment by G6EJD** [comment]
You’ve not told me what hardware your using but usually there is sn adjustment pot your turn for maximum sensitivity

**Comment by G6EJD** [comment]
ESP32 is usually pin 39 the pot is 10-turn!

**Comment by Smruti1919** [comment]
> You’ve not told me what hardware your using but usually there is sn adjustment pot your turn for maximum sensitivity

All exact components mentioned in the video

**Comment by Smruti1919** [comment]
> > You’ve not told me what hardware your using but usually there is sn adjustment pot your turn for maximum sensitivity
> 
> All exact components mentioned in the video

Just the ESP32 pins are bit different thats why I was asking about AO pin of microphone to which pin of ESP32 ??

**Comment by Smruti1919** [comment]
The display isnt showing anything !!

**Comment by Smruti1919** [comment]
> ESP32 is usually pin 39 the pot is 10-tuWhat does this mean i should turn the knob 10 rounds clockwise ??

**Comment by G6EJD** [comment]
This is not my code version and is not really designed for the oled display. Try serial.println(A0) to see what pin it’s using

**Comment by Smruti1919** [comment]
Where should I use serial.println in the code ?

**Comment by G6EJD** [comment]
Start of setup

**Comment by Smruti1919** [comment]
How do you figure out what pin is it using ??

**Comment by Smruti1919** [comment]
Hey now its working....but its printing some random words

**Comment by Smruti1919** [comment]
How to reduce the WPM ??

**Comment by G6EJD** [comment]
It automatically adjusts to wpm more likely your audio source is highly distorted or the microphone needs more adjustment

**Comment by Smruti1919** [comment]
How to adjust microphone ?
