### ISSUE TITLE
How to adjust microphone ?

### ISSUE THREAD

**Issue by Smruti1919** [G6EJD/ESP32-Morse-Decoder#2]
How to adjust microphone ?

**Comment by G6EJD** [comment]
Apply a constant tone and use ide plotter to monitor output adjust for good shape

**Comment by G6EJD** [comment]
Add a serial.println(magnitude) in the main loop

**Comment by Smruti1919** [comment]
How to add constant tone ?

**Comment by Smruti1919** [comment]
What is a good shape ?
![image](https://user-images.githubusercontent.com/48862745/54881373-1a3f3180-4e75-11e9-8a40-95e93a1bdaf1.png)

**Comment by G6EJD** [comment]
I can see your microphone is incorrectly adjusted and needs moving up the scale so it’s balanced top and bottom

**Comment by Smruti1919** [comment]
I dont witness any change my rotating the knob on the microphone unit !!

**Comment by G6EJD** [comment]
Well then your audio is not clean enough do you have a tone generator ?

**Comment by Smruti1919** [comment]
No I dont have a tone generator and the audio file I'm using is the one attached above

**Comment by G6EJD** [comment]
Add a capacitor between your microphone and ESP ADC input, say 1uF or 0.1uF just about any large value will do. Link to your microphone so I can see what it is?

**Comment by Smruti1919** [comment]
Which is the ADC input ?
Is it the SW pin of esp32 ?

**Comment by Smruti1919** [comment]
My current pin connections are

esp32(5v) to Microphone unit(plus) to oled (Vcc)
esp32(SW) to  Microphone unit(AO)
esp32(GND) to  oled(gnd) to Microphone unit(G)
esp32(P17) to  oled(SDA)
esp32(P16)  to  oled(SCL)

**Comment by Smruti1919** [comment]
I have 100uF and 220uF capacitor available with me

**Comment by Smruti1919** [comment]
I have 10uF,100uF and 220uF available with me

**Comment by G6EJD** [comment]
Where you are connecting the audio input

**Comment by G6EJD** [comment]
Either will do 100uF preferred and + to the microphone

**Comment by Smruti1919** [comment]
> Where you are connecting the audio input

Im giving it to the microphone from my phone

**Comment by G6EJD** [comment]
This is why the audio is poor I suspect leading to poor decoding, you really need to be getting audio from a communications reciever

**Comment by Smruti1919** [comment]
How do I do that ??

**Comment by G6EJD** [comment]
OK, this project is a Morse decoder that needs a reasonable source of audio, usually from a communications receiver. Alternatively you can play the sample audio files and the decoder's microphone when correctly adjusted and with not too much audio it will decode Morse.
