### ISSUE TITLE
Mistakes in your software license

### ISSUE THREAD

**Issue by BrucePerens** [G6EJD/ESP32-Morse-Decoder#4]
Hi David,

You have reason to be proud of the ideas and concepts in your software, but the copyright law of your nation (and all others) doesn't allow you to copyright concepts and ideas, which you have attempted to claim in your license text. To do this, you would have had to file a patent before disclosing the work to the public. There is a little explanation by the UK Copyright Authority at https://copyrightservice.co.uk/services/knowledge-base/kb_idea

It would be best to use a license written by a legal professional, as courts generally find problems in enforcing licenses written without sufficient understanding of the underlying law. The GPL or Affero GPL would fit your intent reasonably well.

Thanks

Bruce

**Comment by G6EJD** [comment]
Bruce,

It’s simple, if you don’t like the copyright clauses then don’t use the software, no one is forcing you.

Once an person commits any material to paper or any form of storage medium they own the copyright, it’s a fundamental right to assert copyright.

I’m not sure what your problem is, other than being magnanimous and supercilious.

Regards

David

**Comment by BrucePerens** [comment]
I really tried to be nice only to be answered with abuse.

You pirated the work of Hjalmar Skovholm Hansen, which was published under the GPL. Sticking another license on someone else's copyrighted work and distributing it as your own was not your legal right, and that's why this is piracy. It is still under the GPL, and I will re-port it to ESP-32 without you and your abusive spirit and wrong ideas about copyright. I'm sorry that this is necessary, you could have taken the high road.

**Comment by G6EJD** [comment]
Whatever, write your own code from scratch
